# Database Migrations (Alembic)

## Purpose

This `migrations` directory is managed by Alembic and contains the history of schema changes for the Kairos BCP application's PostgreSQL database. Its primary goal is to enable version control for the database schema, allowing for reliable and repeatable schema updates across different environments (development, testing, production).

## Key Components

* **`versions/`**: This subdirectory holds the individual migration scripts generated by Alembic. Each script represents a set of changes to upgrade or downgrade the database schema.
* `script.py.mako`: Template for new migration scripts.
* `env.py`: Alembic environment configuration script, which sets up how migrations are run.

(Note: `alembic.ini` in the project root is the main configuration file for Alembic.)

## Usage

Database schema changes should not be made manually. Instead, use Alembic commands to:
1.  Generate new migration scripts (after changing SQLAlchemy models in `infrastructure/persistence/sqlalchemy/models.py`).
2.  Apply migrations to update the database schema.
3.  Downgrade migrations if necessary.

## Design Rationale

Using Alembic for database migrations ensures that schema changes are systematic, versioned, and can be reliably applied. This is crucial for maintaining database integrity and consistency throughout the development lifecycle and in production deployments.
